### ISSUE TITLE
Homebridge doesn't start

### ISSUE THREAD

**Issue by jaumebosch** [Dids/homebridge-melcloud-ts#1]
This appear when launching homebridge, if you need more info, please ask

pi@Homebridge:~ $ homebridge -I
[10/27/2020, 1:12:45 AM] Loaded config.json with 0 accessories and 3 platforms.
[10/27/2020, 1:12:46 AM] ---
[10/27/2020, 1:12:48 AM] Loaded plugin: homebridge-config-ui-x@4.30.0
[10/27/2020, 1:12:48 AM] Registering platform 'homebridge-config-ui-x.config'
[10/27/2020, 1:12:48 AM] ---
[10/27/2020, 1:12:48 AM] **The plugin "homebridge-melcloud-ts" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin!**
[10/27/2020, 1:12:51 AM] Loaded plugin: homebridge-melcloud-ts@0.3.7
[10/27/2020, 1:12:51 AM] Registering platform 'homebridge-melcloud-ts.MELCloud'
[10/27/2020, 1:12:51 AM] ---
[10/27/2020, 1:12:54 AM] Loaded plugin: homebridge-samsung-tizen@4.3.3
[10/27/2020, 1:12:54 AM] Registering platform 'homebridge-samsung-tizen.SamsungTizen'
[10/27/2020, 1:12:54 AM] ---
[10/27/2020, 1:12:54 AM] Loading 3 platforms...
[10/27/2020, 1:12:54 AM] [Config] Initializing config platform...
[10/27/2020, 1:12:54 AM] [Config] Spawning homebridge-config-ui-x with PID 3576
[10/27/2020, 1:12:54 AM] [SamsungTizen] Initializing SamsungTizen platform...
[10/27/2020, 1:12:54 AM] [MELCloud] Initializing MELCloud platform...
[10/27/2020, 1:12:55 AM] **ReferenceError: ICharacteristic is not defined
    at new MELCloudPlatform (/usr/local/lib/node_modules/homebridge-melcloud-ts/dist/index.js:366:47)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:395:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)**
[10/27/2020, 1:12:55 AM] Got SIGTERM, shutting down Homebridge...

**Comment by bjornand1** [comment]
Hi, I experience the same issue today, Homebridge won't restart due to error messages related to this plugin. I had to take it out of my config, hope there is a fix?

**Comment by ulumios** [comment]
yes downgrade to homebridge-melcloud-ts v0.3.5 
`sudo npm install -g homebridge-melcloud-ts@0.3.5`

**Comment by bjornand1** [comment]
> yes downgrade to homebridge-melcloud-ts v0.3.5
> `sudo npm install -g homebridge-melcloud-ts@0.3.5`

Thanks for the tip, but even when using this install command, I end up with 3.7 and the same problem...

**Comment by bjornand1** [comment]
Sorry, got 3.5 now and it works again, thanks!

**Comment by bjornand1** [comment]
Any news on this? Does 3.7 work for other people?

**Comment by Zepedrofig** [comment]
Hey! Kinda noob at homebridge and decided to start with this plugin. I have edited the config file to add the user and the password but nothing seems to be happening. I don't get any info on the logs even after I restart the server. What am I missing here?
Thanks in advance!

**Comment by SaM-1993** [comment]
3.7 shuts down my Homebridge too. In 3.5 HomeKit finds no new devices. Do I need to reinstall the ACs in MelCloud app?

**Comment by ulumios** [comment]
3.5 Still works if you set it up propperly. Have you entered your login data in [config.json ](https://github.com/Dids/homebridge-melcloud-ts/blob/master/config.json)

**Comment by SaM-1993** [comment]
> 3.5 Still works if you set it up propperly. Have you entered your login data in [config.json ](https://github.com/Dids/homebridge-melcloud-ts/blob/master/config.json)

Yes. 3.5 works well but I had to remove the ACs from MELCloud app and add them back. After that the Home app found them instantly.

**Comment by maeivi** [comment]
is the project dead, or what?
