### ISSUE TITLE
homebridge warning

### ISSUE THREAD

**Issue by majchrzak-dev** [Dids/homebridge-melcloud-ts#7]
ReferenceError: ICharacteristic is not defined
    at new MELCloudPlatform (/usr/local/lib/node_modules/homebridge-melcloud-ts/dist/index.js:366:47)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)

**Comment by FrodoVDR** [comment]
Same here
